### ISSUE TITLE
Secret in version "v1" cannot be handled as a Secret: illegal base64 data at input byte 4\n

### ISSUE THREAD

**Issue by Johncs2d** [OneUptime/helm-chart#7]
Hi, 

when trying to deploy oneuptime to aws eks using CDK, the deploy fails and its raising this issue. I tried to look where might be the issue is but I can't seem to be to find it.

Im using external postgresql and redis.

values.yaml
```
host: oneuptime.mydomain.com

httpProtocol: http

oneuptimeIngress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
  hosts:
    - oneuptime.mydomain.com

logLevel: DEBUG

postgresql:
  enabled: false

externalPostgres:
  host: server.us-west-2.rds.amazonaws.com
  port: 5432
  username: postgres
  password: 'mylongpassword'
  database: oneuptime

clickhouse:
  fullnameOverride: "ch"

redis:
  enabled: false

externalRedis:
  host: 'cache.usw2.cache.amazonaws.com'
  port: 6379
  password: ''
```

![image](https://github.com/OneUptime/helm-chart/assets/34950240/92047b37-fd57-4505-8d62-3d601fbd69c8)

Thank you for your help in advance.
